package defs
var LiveRoomDefaultConfig = LiveRoomAllConfig{
	Qorder:1,
	Prepic:"http://pic-cloud-bupt.oss-cn-beijing.aliyuncs.com/%E7%BE%8E%E5%9B%BD%E5%BE%80%E4%BA%8B.jpg",
	LivePic:"http://pic-cloud-bupt.oss-cn-beijing.aliyuncs.com/%E7%BE%8E%E5%9B%BD%E5%BE%80%E4%BA%8B.jpg",
	Danmu:1,
	Chat:1,
	Share:1,
	ShareText:"欢迎来到金艺林的直播间",
	Advertisement:0,
	AdJumpUrl:"",
	AdPicUrl:"",
	AdText:"",
	Condition:1,
	ConditionType:0, //表示没有观看条件的设置
    Duration:0, //0表示没有观看有效期的设置
    Price:0,
    TryToSee:0,
    VerificationCode:"",
    Delay:0,
    Transcode:1,
    TranscodeType:[]int{1,2,3,4},
    Record:0,
    RecordType:0,
    Logo:1,
    LogoUrl:"http://pic-cloud-bupt.oss-cn-beijing.aliyuncs.com/%E7%BE%8E%E5%9B%BD%E5%BE%80%E4%BA%8B.jpg",
    LogoPosition:1,
    LogoTransparency:100,
    Lamp:0,
    LampType:1,
    LampText:"",
    LampFontSize:20,
    LampTransparency:100,
    WhiteSiteList:"",
    BlackSiteList:"",
    LiveRoomInfo:LiveRoomIdentity{},
}